name: PR updater
description: Keep your auto-merged pull requests up to date with base branch
inputs:
    token:
        required: true
        description: "Token to perform api calls"
    head:
        required: true
        description: "Your master branch"
    branch:
        required: true
        description: "Current branch"

runs:
    using: node12
    main: bin/index.js

branding:
    icon: git-pull-request
    color: green
