name: Node.js Check

concurrency:
    group: nodejs-${{ github.ref }}
    cancel-in-progress: true

on: [pull_request]

jobs:
    check-changes:
        uses: ./.github/workflows/check-changes.yml

    Tests:
        needs: check-changes
        if: |
            !(
              needs.check-changes.outputs.is_only_tests_changed == 'true'
            )
        runs-on: self-hosted
        defaults:
            run:
                working-directory: server

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install main modules
              run: |
                  cd ../
                  yarn install --frozen-lockfile
            - name: Install server modules
              run: yarn install --frozen-lockfile
            - name: Lint
              run: yarn eslint
            - name: Check Types
              run: yarn checkTypes
            - name: Tests
              run: yarn test
