name: PR update

on:
    schedule:
        - cron: "* * * * *"
    workflow_dispatch:

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: update all prs
              uses: ./
              with:
                  token: ${{ secrets.ACTION_TOKEN }}
                  head: "main"
