name: PR update

on:
    schedule:
        - cron: "* * * * *"
    workflow_dispatch:
    pull_request:

jobs:
    autoupdate:
        runs-on: ubuntu-latest
            permissions:
              actions: read
              contents: read
              security-events: write
        steps:
            - uses: actions/checkout@v3
            - name: update all prs
              uses: ./
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  head: "main"
                  requiredChecks: |
                      build (ubuntu-latest) (push) 
                      build (windows-latest) (push)
