name: "action-test"
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: GithubActionTastingOrg/AutoMergeAction@v1.2
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
