name: "action-test"
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ../../action.yml
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
