name: Update branch

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - labeled
    check_suite:
        types:
            - completed

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    update-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: lcdsmao/update-branch@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  requiredLabels: auto-merge
                  requiredApprovals: 1
                  requiredStatusChecks: |
                      build_pr
                      WIP
